In [2]:
import numpy as np
import cv2
arr1 = np.array([i for i in range(10)])
print(arr1)
arr2 = np.array(arr1,dtype = 'float32')
print(arr2)
arr3 = np.array([1,2,3],np.float32)
print(arr3)
arr4 = np.uint8([[1],[2]])
print(arr4)
arr5 = np.array([1,2,3.0])
print(arr5)

np.zeros((1,5,3),dtype=int)
np.full((2,2),2.0)
np.random.randint(0,10,10)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[1. 2. 3.]
[[1]
 [2]]
[1. 2. 3.]


array([4, 8, 7, 7, 5, 5, 0, 7, 3, 2])

In [4]:
x = np.arange(10).reshape(2,-1)
x.ndim
x.shape
#x.reshape(2,5)
a=np.sum(x[1])
print(a)

35


In [31]:
x = np.arange(10)
y1,y2,y3 = np.split(x,[3,7])
y2

array([3, 4, 5, 6])